Version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Dockerfile base image(s)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Requirements
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

